---
plugin:
  version: 1.0.0
  autoUpdate: false
teleport:
  wait: 10
level: hub
messages:
  runingame: Please run this command ingame
  messagetoplayer: You died
  messagetoplayerrespawn: You respawned
  killedbyunknown: '{PLAYER} died'
  killedby: '{PLAYER} was killed by {KILLER}'
  killedbyprojectile: '{PLAYER} was shot by {KILLER}'
...
